import { Box, Typography } from "@mui/material";

export const rows = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: "30",
    phone: "+1234567890",
    access: "user",
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob.smith@example.com",
    age: "25",
    phone: "+1987654321",
    access: "admin",
  },
  {
    id: 3,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    age: "35",
    phone: "+1122334455",
    access: "Manager",
  },
  {
    id: 4,
    name: "David Wilson",
    email: "david.wilson@example.com",
    age: "40",
    phone: "+4455667788",
    access: "Manager",
  },
  {
    id: 5,
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    age: "27",
    phone: "+9988776655",
    access: "user",
  },
  {
    id: 6,
    name: "James Brown",
    email: "james.brown@example.com",
    age: "33",
    phone: "+7766554433",
    access: "admin",
  },
  {
    id: 7,
    name: "Olivia Miller",
    email: "olivia.miller@example.com",
    age: "29",
    phone: "+3344556677",
    access: "user",
  },
  {
    id: 8,
    name: "William Taylor",
    email: "william.taylor@example.com",
    age: "45",
    phone: "+1122334455",
    access: "admin",
  },
  {
    id: 9,
    name: "Emma Moore",
    email: "emma.moore@example.com",
    age: "32",
    phone: "+9988776655",
    access: "user",
  },
];
